### ISSUE TITLE
It seems that it cannot recognise add implicit crafts

### ISSUE THREAD

**Issue by random1840** [ryanbarr/harvest-monster#49]

**Comment by ryanbarr** [comment]
Hey @random1840, thanks for your report.

Do you by chance have a screenshot of the implicit crafts you're trying to add?

This example screenshot I have seems to recognize both of these implicit crafts: 
![image](https://user-images.githubusercontent.com/427133/180504355-b7a44fb0-de43-44f9-bdce-f1237113eaa3.png)

**Comment by random1840** [comment]
Hi, thanks for your reply. This is the screenshot and I just tried again. 
![cluster](https://user-images.githubusercontent.com/33853602/180607752-a23a6dfb-89f2-4e98-aafc-af6da0f025a0.png)
![no crafts found](https://user-images.githubusercontent.com/33853602/180607760-cd95d707-0aa5-4cd4-a3c0-e0953678acc1.png)

**Comment by ryanbarr** [comment]
Thanks for the screenshot, @random1840! I am able to reproduce the bug and will have a fix in for the next release. ❤️

**Comment by random1840** [comment]
@ryanbarr Glad to hear that! I really appreciate your work. This is the best harvest tool I've used so far. Good luck!

**Comment by ryanbarr** [comment]
Reopening this so we can close it with the correct release. Thanks again!
